name: hospital-monitor
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - opencv
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - plotly
  - pillow
  - ultralytics
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::cpuonly
  - pip:
    - streamlit>=1.28.0
